// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentHistory struct {
	ID        string
	OrderId   string
	CreatedAt pgtype.Timestamptz
	Status    interface{}
}
