// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package models

import (
	"context"
)

const createHistory = `-- name: CreateHistory :exec
INSERT INTO
  public."PaymentHistory"("orderId", "status")
VALUES
  ($1, $2)
`

type CreateHistoryParams struct {
	OrderId string
	Status  interface{}
}

// queries.sql
func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) error {
	_, err := q.db.Exec(ctx, createHistory, arg.OrderId, arg.Status)
	return err
}
