// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package models

import (
	"context"
	"time"
)

const createHistory = `-- name: CreateHistory :exec
INSERT INTO
  public."PaymentHistory"("orderId", "status")
VALUES
  ($1, $2)
`

type CreateHistoryParams struct {
	OrderId string
	Status  interface{}
}

// queries.sql
func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) error {
	_, err := q.db.Exec(ctx, createHistory, arg.OrderId, arg.Status)
	return err
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE
  public."Order"
SET
  status = $1,
  "confirmedAt" = $2
WHERE
  id = $3
`

type UpdateOrderParams struct {
	Status      interface{}
	ConfirmedAt *time.Time
	ID          string
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.Exec(ctx, updateOrder, arg.Status, arg.ConfirmedAt, arg.ID)
	return err
}
