version: '3.8'

services:
  db:
    container_name: postgres
    image: bitnami/postgresql:16
    env_file:
      - ./env/postgres/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uniform-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.2
    env_file:
      - ./env/pgadmin/pgadmin.env
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
    networks:
      - uniform-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file:
      - ./env/rabbit/rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - uniform-network

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    env_file:
      - ./env/mongo/mongodb.env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - uniform-network

volumes:
  postgres_data:
  rabbitmq_data:
  mongodb_data:
  grafana-storage:

networks:
  uniform-network:
    driver: bridge
